server:
  port: 0

spring:

  application:
    name: ProductsMicroservice

  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
      acks: all
      retries: 10
      properties:
        retry.backoff.ms: 1000
        max.in.flight.requests.per.connection: 5
        enable.idempotence: true
#        delivery.timeout.ms: 120000
#        linger.ms: 0
#        request.timeout.ms: 30000
